name: GitHub Container Registry Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tags
        id: image-tags
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY_OWNER}/webmap"
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "TAGS=${IMAGE_NAME}:latest" >> "$GITHUB_OUTPUT"
          elif [[ "${GITHUB_REF}" =~ ^refs/tags/(v[0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            VERSION="${BASH_REMATCH[1]}"
            echo "TAGS=${IMAGE_NAME}:${VERSION},${IMAGE_NAME}:latest" >> "$GITHUB_OUTPUT"
          else
            SHORT_SHA="${GITHUB_SHA:0:8}"
            echo "TAGS=${IMAGE_NAME}:${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.image-tags.outputs.TAGS }}

      - name: Generate artifact attestation
        if: always()
        uses: actions/attest-build-provenance@v3
        with:
          push-to-registry: true
          subject-name: ghcr.io/${{ github.repository_owner }}/webmap
          subject-digest: ${{ steps.push.outputs.digest }}
          predicate-type: "https://in-toto.io/attestation/release/v0.1"
          predicate: '{"purl":"pkg:oci/..."}'
